### ISSUE TITLE
import failure on M1 

### ISSUE THREAD

**Issue by RELNO** [doorleyr/cityIO_Flask#2]
The following issue happens when trying to run on macOS M1 laptop:
```
Traceback (most recent call last):
  File "/Users/___/cityIO_Flask/cityio_lite.py", line 13, in <module>
    from cityio import module_hash
ImportError: dlopen(/Users/___/cityIO_Flask/cityio.so, 0x0002): tried: '/Users/___/cityIO_Flask/cityio.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

```

I tried to follow some suggestions to install a newer python version, but it didn't work.

**Comment by doorleyr** [comment]
I removed the cityio.so module. Now it just uses python's hashlib for the hash function.

**Comment by RELNO** [comment]
looks like it's working now, will take it a deeper look and report. 
I've got a few changes to suggest, can you fork this to a new CS repo and I'll pr?
